"""ajuestes

Revision ID: 02be66f921e8
Revises: 214757ff6eb7
Create Date: 2025-04-27 15:15:45.809013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02be66f921e8'
down_revision: Union[str, None] = '214757ff6eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shopping_list_ingredient_id_fkey', 'shopping_list', type_='foreignkey')
    op.drop_column('shopping_list', 'ingredient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shopping_list_ingredient_id_fkey', 'shopping_list', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
