"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 032f5038aa5a
Revises: 91061a24b22a
Create Date: 2025-04-18 00:27:00.846482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032f5038aa5a'
down_revision: Union[str, None] = '91061a24b22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('post_like', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('post_like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('post_like_comment_id_fkey', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'user', ['user_id'], ['id'])
    op.drop_column('post_like', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_comment_id_fkey', 'post_like', 'like', ['comment_id'], ['id'])
    op.alter_column('post_like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('post_like', 'user_id')
    op.drop_column('post_like', 'id')
    # ### end Alembic commands ###
