"""add indexes to foreign keys

Revision ID: 0619b94573c1
Revises: 0eca5babf47b
Create Date: 2025-03-26 21:39:11.388613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0619b94573c1'
down_revision: Union[str, None] = '0eca5babf47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_session_id', table_name='recipe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recipe_session_id', 'recipe', ['session_id'], unique=False)
    # ### end Alembic commands ###
