"""midia sosial

Revision ID: 0735afc1cd43
Revises: ba573cb4e89f
Create Date: 2025-04-17 17:29:26.302605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0735afc1cd43'
down_revision: Union[str, None] = 'ba573cb4e89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('midia_post_id_fkey', 'midia', type_='foreignkey')
    op.drop_column('midia', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('midia', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('midia_post_id_fkey', 'midia', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
