"""descrição da migration

Revision ID: 0dcc641a529c
Revises: 9014c5463a2b
Create Date: 2025-02-13 00:06:30.684700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcc641a529c'
down_revision: Union[str, None] = '9014c5463a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
