"""midia sosial

Revision ID: 10cf96fb8a5e
Revises: 7107e9e1a3f6
Create Date: 2025-04-17 22:46:11.574371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cf96fb8a5e'
down_revision: Union[str, None] = '7107e9e1a3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'post_id')
    )
    op.drop_table('likes')
    op.drop_table('posts')
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('image_recipe_id_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_post_midia_midia_id'), 'post_midia', ['midia_id'], unique=False)
    op.create_index(op.f('ix_post_midia_post_id'), 'post_midia', ['post_id'], unique=False)
    op.drop_constraint('post_midia_post_id_fkey', 'post_midia', type_='foreignkey')
    op.create_foreign_key(None, 'post_midia', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_midia', type_='foreignkey')
    op.create_foreign_key('post_midia_post_id_fkey', 'post_midia', 'posts', ['post_id'], ['id'])
    op.drop_index(op.f('ix_post_midia_post_id'), table_name='post_midia')
    op.drop_index(op.f('ix_post_midia_midia_id'), table_name='post_midia')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_recipe_id_fkey', 'image', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('posts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='likes_pkey')
    )
    op.drop_table('like')
    op.drop_table('post')
    # ### end Alembic commands ###
