"""index

Revision ID: 1e55db11b753
Revises: dc83c1669fe3
Create Date: 2025-03-25 23:20:33.304505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector  # 👈 importante!

# revision identifiers, used by Alembic.
revision: str = '1e55db11b753'
down_revision: Union[str, None] = 'dc83c1669fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'embedding')
    # ### end Alembic commands ###
