"""shopping list

Revision ID: 1f24bc5aea5a
Revises: 41794b492461
Create Date: 2025-04-21 15:47:02.802097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f24bc5aea5a'
down_revision: Union[str, None] = '41794b492461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_item', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shopping_item', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_item', 'updated_at')
    op.drop_column('shopping_item', 'created_at')
    # ### end Alembic commands ###
