"""ajuestes

Revision ID: 214b40bf697b
Revises: a700c5dac635
Create Date: 2025-04-27 14:54:12.609426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214b40bf697b'
down_revision: Union[str, None] = 'a700c5dac635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_list', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_list', type_='foreignkey')
    op.drop_column('shopping_list', 'ingredient_id')
    # ### end Alembic commands ###
