"""ajuestes

Revision ID: 2baa46295ba0
Revises: 7a1311103dcc
Create Date: 2025-04-27 14:24:07.263104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2baa46295ba0'
down_revision: Union[str, None] = '7a1311103dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_item_id', table_name='shopping_item')
    op.drop_index('ix_shopping_item_name', table_name='shopping_item')
    op.drop_index('ix_shopping_item_price', table_name='shopping_item')
    op.drop_index('ix_shopping_item_quantity', table_name='shopping_item')
    op.drop_index('ix_shopping_item_shopping_list_id', table_name='shopping_item')
    op.drop_index('ix_shopping_item_unity', table_name='shopping_item')
    op.drop_table('shopping_item')
    op.add_column('ingredient', sa.Column('shopping_list_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ingredient_shopping_list_id'), 'ingredient', ['shopping_list_id'], unique=False)
    op.create_foreign_key(None, 'ingredient', 'shopping_list', ['shopping_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_index(op.f('ix_ingredient_shopping_list_id'), table_name='ingredient')
    op.drop_column('ingredient', 'shopping_list_id')
    op.create_table('shopping_item',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shopping_list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_list.id'], name='shopping_item_shopping_list_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shopping_item_pkey')
    )
    op.create_index('ix_shopping_item_unity', 'shopping_item', ['unity'], unique=False)
    op.create_index('ix_shopping_item_shopping_list_id', 'shopping_item', ['shopping_list_id'], unique=False)
    op.create_index('ix_shopping_item_quantity', 'shopping_item', ['quantity'], unique=False)
    op.create_index('ix_shopping_item_price', 'shopping_item', ['price'], unique=False)
    op.create_index('ix_shopping_item_name', 'shopping_item', ['name'], unique=False)
    op.create_index('ix_shopping_item_id', 'shopping_item', ['id'], unique=False)
    # ### end Alembic commands ###
