"""midia sosial

Revision ID: 2c3f479f04ad
Revises: 0735afc1cd43
Create Date: 2025-04-17 17:54:18.766706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3f479f04ad'
down_revision: Union[str, None] = '0735afc1cd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_midia',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('midia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['midia_id'], ['midia.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'midia_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_midia')
    # ### end Alembic commands ###
