"""ajueste

Revision ID: 3334f2be4fc3
Revises: 19969074431c
Create Date: 2025-03-01 18:10:06.697353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3334f2be4fc3'
down_revision: Union[str, None] = '19969074431c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('name', sa.String(), nullable=True))
    op.add_column('plan', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_plan_type', table_name='plan')
    op.create_index(op.f('ix_plan_description'), 'plan', ['description'], unique=False)
    op.create_index(op.f('ix_plan_name'), 'plan', ['name'], unique=False)
    op.drop_column('plan', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plan_name'), table_name='plan')
    op.drop_index(op.f('ix_plan_description'), table_name='plan')
    op.create_index('ix_plan_type', 'plan', ['type'], unique=False)
    op.drop_column('plan', 'description')
    op.drop_column('plan', 'name')
    # ### end Alembic commands ###
