"""ajuestes

Revision ID: 3a926ca0d0f5
Revises: 8ef93adb7459
Create Date: 2025-02-23 10:38:59.787760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a926ca0d0f5'
down_revision: Union[str, None] = '8ef93adb7459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
