"""shopping list

Revision ID: 41794b492461
Revises: dbee865ebc31
Create Date: 2025-04-21 15:35:15.209984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41794b492461'
down_revision: Union[str, None] = 'dbee865ebc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_item', sa.Column('shopping_list_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_shopping_item_shopping_list_id'), 'shopping_item', ['shopping_list_id'], unique=False)
    op.create_foreign_key(None, 'shopping_item', 'shopping_list', ['shopping_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_item', type_='foreignkey')
    op.drop_index(op.f('ix_shopping_item_shopping_list_id'), table_name='shopping_item')
    op.drop_column('shopping_item', 'shopping_list_id')
    # ### end Alembic commands ###
