"""ajuestes

Revision ID: 41fb5cab2a9a
Revises: 9dfb73cd23f0
Create Date: 2025-05-14 13:22:38.520578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fb5cab2a9a'
down_revision: Union[str, None] = '9dfb73cd23f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_counter_id'), 'click_counter', ['id'], unique=False)
    op.create_table('contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('restaurante', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_message_id'), 'contact_message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_message_id'), table_name='contact_message')
    op.drop_table('contact_message')
    op.drop_index(op.f('ix_click_counter_id'), table_name='click_counter')
    op.drop_table('click_counter')
    # ### end Alembic commands ###
