"""add fields

Revision ID: 47cbc691a57a
Revises: 6ff2a7e668d5
Create Date: 2025-02-16 09:13:03.359147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cbc691a57a'
down_revision: Union[str, None] = '6ff2a7e668d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('description', sa.String(), nullable=False))
    op.add_column('recipe', sa.Column('preparation_time', sa.String(), nullable=False))
    op.add_column('recipe', sa.Column('serving_size', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'serving_size')
    op.drop_column('recipe', 'preparation_time')
    op.drop_column('recipe', 'description')
    # ### end Alembic commands ###
