"""ajuestes

Revision ID: 4a1e8c360841
Revises: 704ea4c5caeb
Create Date: 2025-02-22 16:58:23.568497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1e8c360841'
down_revision: Union[str, None] = '704ea4c5caeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('icon_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'icon_name')
    # ### end Alembic commands ###
