"""ajuestes

Revision ID: 50548a70e110
Revises: 4ce5266a0724
Create Date: 2025-04-24 17:38:59.425753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50548a70e110'
down_revision: Union[str, None] = '4ce5266a0724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'img',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'sem imagem'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'img',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'sem imagem'::character varying"))
    # ### end Alembic commands ###
