"""ajuste nos relacionamentos post-midia

Revision ID: 54c9a646eef5
Revises: 878a5089ace2
Create Date: 2025-04-17 23:35:58.010182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c9a646eef5'
down_revision: Union[str, None] = '878a5089ace2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
