"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 5c97893a255a
Revises: a51590a7c783
Create Date: 2025-04-18 09:36:35.450909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c97893a255a'
down_revision: Union[str, None] = 'a51590a7c783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_midia_post_id', table_name='midia')
    op.drop_constraint('midia_post_id_fkey', 'midia', type_='foreignkey')
    op.drop_column('midia', 'post_id')
    op.add_column('recipe', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipe_post_id'), 'recipe', ['post_id'], unique=False)
    op.create_foreign_key(None, 'recipe', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_post_id'), table_name='recipe')
    op.drop_column('recipe', 'post_id')
    op.add_column('midia', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('midia_post_id_fkey', 'midia', 'post', ['post_id'], ['id'])
    op.create_index('ix_midia_post_id', 'midia', ['post_id'], unique=False)
    # ### end Alembic commands ###
