"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 5ccab8327ccc
Revises: ad1e38651782
Create Date: 2025-04-18 17:42:34.537531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccab8327ccc'
down_revision: Union[str, None] = 'ad1e38651782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creator_nick_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_creator_nick_name'), 'user', ['creator_nick_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_creator_nick_name'), table_name='user')
    op.drop_column('user', 'creator_nick_name')
    # ### end Alembic commands ###
