"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 5e08226cc823
Revises: 5c97893a255a
Create Date: 2025-04-18 10:35:26.630468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e08226cc823'
down_revision: Union[str, None] = '5c97893a255a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'recipe_id')
    # ### end Alembic commands ###
