"""ajueste

Revision ID: 5ff5ac9b22b9
Revises: 3334f2be4fc3
Create Date: 2025-03-01 18:19:48.165292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff5ac9b22b9'
down_revision: Union[str, None] = '3334f2be4fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'plan_id')
    # ### end Alembic commands ###
