"""ajustes

Revision ID: 649ca0db954c
Revises: 7ede0c915e0d
Create Date: 2025-04-22 13:01:15.947783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649ca0db954c'
down_revision: Union[str, None] = '7ede0c915e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('name', sa.String(), server_default='sem nome', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'name')
    # ### end Alembic commands ###
