"""ajuestes

Revision ID: 680a5ed13bf3
Revises: 64cff96a2328
Create Date: 2025-03-05 21:20:00.294816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680a5ed13bf3'
down_revision: Union[str, None] = '64cff96a2328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('dificulty', sa.String(), server_default='Fácil', nullable=False))
    op.add_column('recipe', sa.Column('portions', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'portions')
    op.drop_column('recipe', 'dificulty')
    # ### end Alembic commands ###
