"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 69231bdd5188
Revises: 8a7a2d0528ae
Create Date: 2025-04-18 00:47:13.269592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69231bdd5188'
down_revision: Union[str, None] = '8a7a2d0528ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like')
    op.drop_table('post_midia')
    op.drop_table('post_comment')
    op.drop_table('comment_user')
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_post_id'), 'comment', ['post_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_index(op.f('ix_like_post_id'), 'like', ['post_id'], unique=False)
    op.add_column('midia', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_midia_post_id'), 'midia', ['post_id'], unique=False)
    op.create_foreign_key(None, 'midia', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'midia', type_='foreignkey')
    op.drop_index(op.f('ix_midia_post_id'), table_name='midia')
    op.drop_column('midia', 'post_id')
    op.drop_index(op.f('ix_like_post_id'), table_name='like')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_post_id'), table_name='comment')
    op.drop_column('comment', 'post_id')
    op.create_table('comment_user',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='comment_user_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id', name='comment_user_pkey')
    )
    op.create_table('post_comment',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='post_comment_comment_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_comment_post_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', 'post_id', name='post_comment_pkey')
    )
    op.create_table('post_midia',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('midia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['midia_id'], ['midia.id'], name='post_midia_midia_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_midia_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'midia_id', name='post_midia_pkey')
    )
    op.create_table('post_like',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('like_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['like_id'], ['like.id'], name='post_like_like_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_like_post_id_fkey')
    )
    # ### end Alembic commands ###
