"""ajuestes

Revision ID: 6aeed0bd47f3
Revises: cf1f18e4a254
Create Date: 2025-04-27 14:35:12.075928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aeed0bd47f3'
down_revision: Union[str, None] = 'cf1f18e4a254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
