"""ajuestes

Revision ID: 704ea4c5caeb
Revises: 3322069a67ac
Create Date: 2025-02-22 16:56:12.976555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704ea4c5caeb'
down_revision: Union[str, None] = '3322069a67ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('collection', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('collection', 'title')
    op.drop_column('collection', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('collection', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('collection', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('collection', 'name')
    # ### end Alembic commands ###
