"""ajueste

Revision ID: 7b0bbcb5b3a0
Revises: a1e0d064a570
Create Date: 2025-07-25 14:43:11.715745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0bbcb5b3a0'
down_revision: Union[str, None] = 'a1e0d064a570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipe_product_id'), 'recipe', ['product_id'], unique=False)
    op.create_foreign_key(None, 'recipe', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_product_id'), table_name='recipe')
    op.drop_column('recipe', 'product_id')
    # ### end Alembic commands ###
