"""ajuestes

Revision ID: 7d43b35fb1f1
Revises: 44ccfa00c9d2
Create Date: 2025-02-23 11:30:26.960333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d43b35fb1f1'
down_revision: Union[str, None] = '44ccfa00c9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
