"""ajustes

Revision ID: 7ede0c915e0d
Revises: fc54245b7a09
Create Date: 2025-04-22 12:44:06.584512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ede0c915e0d'
down_revision: Union[str, None] = 'fc54245b7a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ingredient', sa.Column('unity', sa.String(), server_default='unidade', nullable=False))
    op.add_column('ingredient', sa.Column('price', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ingredient', sa.Column('img', sa.String(), server_default='sem imagem', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'img')
    op.drop_column('ingredient', 'price')
    op.drop_column('ingredient', 'unity')
    op.drop_column('ingredient', 'quantity')
    # ### end Alembic commands ###
