"""ajuste nos relacionamentos post-midia

Revision ID: 878a5089ace2
Revises: 1722b0561301
Create Date: 2025-04-17 23:32:05.947658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878a5089ace2'
down_revision: Union[str, None] = '1722b0561301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
