"""ajsdad

Revision ID: 899f3447047e
Revises: c0dc7ac1cfff
Create Date: 2025-03-26 22:35:59.292727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899f3447047e'
down_revision: Union[str, None] = 'c0dc7ac1cfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('macro_recipe_id_fkey', 'macro', type_='foreignkey')
    op.create_foreign_key(None, 'macro', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'macro', type_='foreignkey')
    op.create_foreign_key('macro_recipe_id_fkey', 'macro', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
