"""juste

Revision ID: 89f8351bb894
Revises: af5c823e7b67
Create Date: 2025-03-15 18:17:54.127024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f8351bb894'
down_revision: Union[str, None] = 'af5c823e7b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_recipe')
    op.drop_constraint('user_plan_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_plan_id_fkey', 'user', 'plan', ['plan_id'], ['id'])
    op.create_table('session_recipe',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='session_recipe_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='session_recipe_session_id_fkey'),
    sa.PrimaryKeyConstraint('recipe_id', 'session_id', name='session_recipe_pkey')
    )
    # ### end Alembic commands ###
