"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 8a7a2d0528ae
Revises: 032f5038aa5a
Create Date: 2025-04-18 00:31:10.942026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7a2d0528ae'
down_revision: Union[str, None] = '032f5038aa5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('like_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_like_comment_id_fkey', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'like', ['like_id'], ['id'])
    op.drop_column('post_like', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_comment_id_fkey', 'post_like', 'like', ['comment_id'], ['id'])
    op.drop_column('post_like', 'like_id')
    # ### end Alembic commands ###
