"""ajuesrtes

Revision ID: 8abb287ede6f
Revises: 89f8351bb894
Create Date: 2025-03-25 13:24:43.054659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abb287ede6f'
down_revision: Union[str, None] = '89f8351bb894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('recipe', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_column('image', 'name')
    # ### end Alembic commands ###
