"""ajuestes

Revision ID: 8f5ee8984f66
Revises: bc68c072cbf1
Create Date: 2025-03-26 19:15:10.274663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f5ee8984f66'
down_revision: Union[str, None] = 'bc68c072cbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ask_recipe_description', table_name='ask_recipe')
    op.drop_index('ix_ask_recipe_id', table_name='ask_recipe')
    op.create_unique_constraint(None, 'ask_recipe', ['description'])
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_index(op.f('ix_collection_user_id'), 'collection', ['user_id'], unique=False)
    op.create_index(op.f('ix_image_recipe_id'), 'image', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_ingredient_recipe_id'), 'ingredient', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_macro_recipe_id'), 'macro', ['recipe_id'], unique=False)
    op.alter_column('order', 'last_payment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_order_amount', table_name='order')
    op.drop_index('ix_order_id', table_name='order')
    op.drop_index('ix_plan_amount', table_name='plan')
    op.drop_index('ix_plan_description', table_name='plan')
    op.drop_index('ix_plan_id', table_name='plan')
    op.drop_index('ix_plan_name', table_name='plan')
    op.drop_index('ix_plan_plan_id', table_name='plan')
    op.create_unique_constraint(None, 'plan', ['plan_id'])
    op.create_index(op.f('ix_preparation_recipe_id'), 'preparation', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_collection_id'), 'recipe', ['collection_id'], unique=False)
    op.create_index(op.f('ix_recipe_session_id'), 'recipe', ['session_id'], unique=False)
    op.drop_column('recipe', 'embedding')
    op.create_index(op.f('ix_recipe_categories_category_id'), 'recipe_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_recipe_categories_recipe_id'), 'recipe_categories', ['recipe_id'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_photo_url', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_photo_url', 'user', ['photo_url'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_recipe_categories_recipe_id'), table_name='recipe_categories')
    op.drop_index(op.f('ix_recipe_categories_category_id'), table_name='recipe_categories')
    op.add_column('recipe', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recipe_session_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_collection_id'), table_name='recipe')
    op.drop_index(op.f('ix_preparation_recipe_id'), table_name='preparation')
    op.drop_constraint(None, 'plan', type_='unique')
    op.create_index('ix_plan_plan_id', 'plan', ['plan_id'], unique=True)
    op.create_index('ix_plan_name', 'plan', ['name'], unique=False)
    op.create_index('ix_plan_id', 'plan', ['id'], unique=False)
    op.create_index('ix_plan_description', 'plan', ['description'], unique=False)
    op.create_index('ix_plan_amount', 'plan', ['amount'], unique=False)
    op.create_index('ix_order_id', 'order', ['id'], unique=False)
    op.create_index('ix_order_amount', 'order', ['amount'], unique=False)
    op.alter_column('order', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'last_payment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_macro_recipe_id'), table_name='macro')
    op.drop_index(op.f('ix_ingredient_recipe_id'), table_name='ingredient')
    op.drop_index(op.f('ix_image_recipe_id'), table_name='image')
    op.drop_index(op.f('ix_collection_user_id'), table_name='collection')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.drop_constraint(None, 'ask_recipe', type_='unique')
    op.create_index('ix_ask_recipe_id', 'ask_recipe', ['id'], unique=False)
    op.create_index('ix_ask_recipe_description', 'ask_recipe', ['description'], unique=True)
    # ### end Alembic commands ###
