"""descrição da migration

Revision ID: 9014c5463a2b
Revises: 91e455f0559e
Create Date: 2025-02-12 23:55:31.761584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9014c5463a2b'
down_revision: Union[str, None] = '91e455f0559e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - ajustados! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('recipeType', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    
    # Adicionando a coluna session_id permitindo NULL temporariamente
    op.add_column('recipe', sa.Column('session_id', sa.Integer(), nullable=True))
    
    # Atualizando registros existentes com um ID válido
    op.execute("UPDATE recipe SET session_id = 1")  # Substitua pelo ID correto caso necessário

    # Agora tornamos a coluna NOT NULL
    op.alter_column('recipe', 'session_id', nullable=False)

    # Ajustando constraint de collection_id
    op.alter_column('recipe', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('recipe_collection_id_fkey', 'recipe', type_='foreignkey')

    # Criando chaves estrangeiras
    op.create_foreign_key(None, 'recipe', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - ajustados! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_collection_id_fkey', 'recipe', 'collection', ['collection_id'], ['id'])
    
    # Reverter para nullable=True antes de remover a coluna
    op.alter_column('recipe', 'session_id', nullable=True)
    
    op.drop_column('recipe', 'session_id')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
