"""ajuestes

Revision ID: 92834dc7cb1d
Revises: eef3ef6b2a98
Create Date: 2025-02-23 10:23:36.018618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92834dc7cb1d'
down_revision: Union[str, None] = 'eef3ef6b2a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
