"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 92cdacb66dc4
Revises: 5ccab8327ccc
Create Date: 2025-04-19 13:14:48.055604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cdacb66dc4'
down_revision: Union[str, None] = '5ccab8327ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creator_start_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'creator_start_at')
    # ### end Alembic commands ###
