"""shopping list

Revision ID: 932b78a2be9a
Revises: fde8e2b87199
Create Date: 2025-04-21 15:14:00.208931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932b78a2be9a'
down_revision: Union[str, None] = 'fde8e2b87199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_item_recipe_id', table_name='shopping_item')
    op.drop_index('ix_shopping_item_user_id', table_name='shopping_item')
    op.drop_constraint('shopping_item_user_id_fkey', 'shopping_item', type_='foreignkey')
    op.drop_constraint('shopping_item_recipe_id_fkey', 'shopping_item', type_='foreignkey')
    op.drop_column('shopping_item', 'recipe_id')
    op.drop_column('shopping_item', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_item', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shopping_item', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shopping_item_recipe_id_fkey', 'shopping_item', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('shopping_item_user_id_fkey', 'shopping_item', 'user', ['user_id'], ['id'])
    op.create_index('ix_shopping_item_user_id', 'shopping_item', ['user_id'], unique=False)
    op.create_index('ix_shopping_item_recipe_id', 'shopping_item', ['recipe_id'], unique=False)
    # ### end Alembic commands ###
