"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 96bacf95c485
Revises: d37f449ca97f
Create Date: 2025-04-18 11:25:07.660685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bacf95c485'
down_revision: Union[str, None] = 'd37f449ca97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_post_id', table_name='recipe')
    op.drop_constraint('recipe_post_id_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_post_id_fkey', 'recipe', 'post', ['post_id'], ['id'])
    op.create_index('ix_recipe_post_id', 'recipe', ['post_id'], unique=False)
    # ### end Alembic commands ###
