"""New revision

Revision ID: 9b6bdf2b2eb2
Revises: cac837360709
Create Date: 2025-03-11 15:34:55.779174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6bdf2b2eb2'
down_revision: Union[str, None] = 'cac837360709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ask_recipe_description'), 'ask_recipe', ['description'], unique=True)
    op.create_index(op.f('ix_ask_recipe_id'), 'ask_recipe', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ask_recipe_id'), table_name='ask_recipe')
    op.drop_index(op.f('ix_ask_recipe_description'), table_name='ask_recipe')
    op.drop_table('ask_recipe')
    # ### end Alembic commands ###
