"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: 9d4e99c7daa0
Revises: e72373d2b82a
Create Date: 2025-04-18 00:17:51.100413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4e99c7daa0'
down_revision: Union[str, None] = 'e72373d2b82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_user',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('comment_user')
    # ### end Alembic commands ###
