"""aju

Revision ID: 9dfb73cd23f0
Revises: 60ac8e335505
Create Date: 2025-05-10 23:59:11.937037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfb73cd23f0'
down_revision: Union[str, None] = '60ac8e335505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('is_premium', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'is_premium')
    # ### end Alembic commands ###
