"""ajueste

Revision ID: 9ecdf7bdc1dd
Revises: 8e31ec47549c
Create Date: 2025-03-01 15:54:21.856819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecdf7bdc1dd'
down_revision: Union[str, None] = '8e31ec47549c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
