"""ajustes

Revision ID: a1e0d064a570
Revises: ba9d87923564
Create Date: 2025-07-22 19:23:04.561879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e0d064a570'
down_revision: Union[str, None] = 'ba9d87923564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_item',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'item_id')
    )
    op.create_index(op.f('ix_product_item_item_id'), 'product_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_product_item_product_id'), 'product_item', ['product_id'], unique=False)
    op.create_table('user_product',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.create_index(op.f('ix_user_product_product_id'), 'user_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_product_user_id'), 'user_product', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_user_id'), table_name='user_product')
    op.drop_index(op.f('ix_user_product_product_id'), table_name='user_product')
    op.drop_table('user_product')
    op.drop_index(op.f('ix_product_item_product_id'), table_name='product_item')
    op.drop_index(op.f('ix_product_item_item_id'), table_name='product_item')
    op.drop_table('product_item')
    # ### end Alembic commands ###
