"""midia sosial

Revision ID: a47f8da55d4b
Revises: 8c9c56e3ed9d
Create Date: 2025-04-17 22:59:18.187664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47f8da55d4b'
down_revision: Union[str, None] = '8c9c56e3ed9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'post_id')
    )
    op.drop_table('likes')
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('image_recipe_id_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_midia_midia_id_fkey', 'post_midia', type_='foreignkey')
    op.create_foreign_key(None, 'post_midia', 'midia', ['midia_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_midia', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_midia', type_='foreignkey')
    op.drop_constraint(None, 'post_midia', type_='foreignkey')
    op.create_foreign_key('post_midia_midia_id_fkey', 'post_midia', 'midia', ['midia_id'], ['id'])
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_recipe_id_fkey', 'image', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.create_table('likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='likes_pkey')
    )
    op.drop_table('like')
    op.drop_table('post')
    # ### end Alembic commands ###
