"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: a51590a7c783
Revises: 69231bdd5188
Create Date: 2025-04-18 00:50:09.711035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51590a7c783'
down_revision: Union[str, None] = '69231bdd5188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
