"""ajuestes

Revision ID: a8b1ad70c064
Revises: 265bd0ff6633
Create Date: 2025-03-26 20:52:37.216639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b1ad70c064'
down_revision: Union[str, None] = '265bd0ff6633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('collection', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_ingredient_title', table_name='ingredient')
    op.create_index(op.f('ix_ingredient_recipe_id'), 'ingredient', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_macro_recipe_id'), 'macro', ['recipe_id'], unique=False)
    op.alter_column('order', 'last_payment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_order_amount', table_name='order')
    op.drop_index('ix_plan_plan_id', table_name='plan')
    op.create_unique_constraint(None, 'plan', ['plan_id'])
    op.drop_index('ix_preparation_title', table_name='preparation')
    op.create_index(op.f('ix_preparation_recipe_id'), 'preparation', ['recipe_id'], unique=False)
    op.drop_index('ix_recipe_title', table_name='recipe')
    op.create_index(op.f('ix_recipe_collection_id'), 'recipe', ['collection_id'], unique=False)
    op.create_index(op.f('ix_recipe_session_id'), 'recipe', ['session_id'], unique=False)
    op.create_index(op.f('ix_recipe_categories_category_id'), 'recipe_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_recipe_categories_recipe_id'), 'recipe_categories', ['recipe_id'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_photo_url', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_photo_url', 'user', ['photo_url'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_recipe_categories_recipe_id'), table_name='recipe_categories')
    op.drop_index(op.f('ix_recipe_categories_category_id'), table_name='recipe_categories')
    op.drop_index(op.f('ix_recipe_session_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_collection_id'), table_name='recipe')
    op.create_index('ix_recipe_title', 'recipe', ['title'], unique=False)
    op.drop_index(op.f('ix_preparation_recipe_id'), table_name='preparation')
    op.create_index('ix_preparation_title', 'preparation', ['title'], unique=False)
    op.drop_constraint(None, 'plan', type_='unique')
    op.create_index('ix_plan_plan_id', 'plan', ['plan_id'], unique=True)
    op.create_index('ix_order_amount', 'order', ['amount'], unique=False)
    op.alter_column('order', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'last_payment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_macro_recipe_id'), table_name='macro')
    op.drop_index(op.f('ix_ingredient_recipe_id'), table_name='ingredient')
    op.create_index('ix_ingredient_title', 'ingredient', ['title'], unique=False)
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.alter_column('collection', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    # ### end Alembic commands ###
