"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: ad1e38651782
Revises: 8f002146aaf7
Create Date: 2025-04-18 17:40:38.580459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1e38651782'
down_revision: Union[str, None] = '8f002146aaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creator_nick_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_creator_nick_name'), 'user', ['creator_nick_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_creator_nick_name'), table_name='user')
    op.drop_column('user', 'creator_nick_name')
    # ### end Alembic commands ###
