"""juste

Revision ID: af5c823e7b67
Revises: dfd1bc0ee4ae
Create Date: 2025-03-15 18:10:08.705414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5c823e7b67'
down_revision: Union[str, None] = 'dfd1bc0ee4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_collection')
    op.add_column('recipe', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'collection', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'collection_id')
    op.create_table('recipe_collection',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name='recipe_collection_collection_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='recipe_collection_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('recipe_id', 'collection_id', name='recipe_collection_pkey')
    )
    # ### end Alembic commands ###
