"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: b00c69c6e813
Revises: 96bacf95c485
Create Date: 2025-04-18 11:29:03.259995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00c69c6e813'
down_revision: Union[str, None] = '96bacf95c485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
