"""ajuestes

Revision ID: b27c102ac505
Revises: cd3b181e6411
Create Date: 2025-02-23 11:17:47.766449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27c102ac505'
down_revision: Union[str, None] = 'cd3b181e6411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bundle_recipe')
    op.drop_table('bundle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bundle_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bundle_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bundle_recipe',
    sa.Column('bundle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], name='bundle_recipe_bundle_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='bundle_recipe_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('bundle_id', 'recipe_id', name='bundle_recipe_pkey')
    )
    # ### end Alembic commands ###
