"""macro taqble

Revision ID: bc68c072cbf1
Revises: c2b57136287a
Create Date: 2025-03-26 01:43:22.437312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc68c072cbf1'
down_revision: Union[str, None] = 'c2b57136287a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_collection_id', table_name='recipe')
    op.drop_index('ix_recipe_session_id', table_name='recipe')
    op.drop_column('recipe', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index('ix_recipe_session_id', 'recipe', ['session_id'], unique=False)
    op.create_index('ix_recipe_collection_id', 'recipe', ['collection_id'], unique=False)
    # ### end Alembic commands ###
