"""macro taqble

Revision ID: c2b57136287a
Revises: 5e2c9dfe7461
Create Date: 2025-03-26 00:34:56.689628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b57136287a'
down_revision: Union[str, None] = '5e2c9dfe7461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('total_kcal', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('percent_kcal', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('carb_percent', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('protein_percent', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('fiber_percent', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('fat_percent', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_id'), 'macro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_id'), table_name='macro')
    op.drop_table('macro')
    # ### end Alembic commands ###
