"""ajueste

Revision ID: cf72cdecad3e
Revises: b74129bf284d
Create Date: 2025-03-01 16:13:43.230000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf72cdecad3e'
down_revision: Union[str, None] = 'b74129bf284d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collection_user_id_fkey', 'collection', type_='foreignkey')
    op.drop_column('collection', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('collection_user_id_fkey', 'collection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
