"""ajuestes

Revision ID: d2e9ea89ff9a
Revises: 5ff5ac9b22b9
Create Date: 2025-03-02 17:29:53.841244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e9ea89ff9a'
down_revision: Union[str, None] = '5ff5ac9b22b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('description', sa.String(), server_default='Sem descrição', nullable=False))
    op.drop_column('ingredient', 'quantity')
    op.add_column('preparation', sa.Column('step', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preparation', 'step')
    op.add_column('ingredient', sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ingredient', 'description')
    # ### end Alembic commands ###
