"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: d37f449ca97f
Revises: dfa59e224900
Create Date: 2025-04-18 11:21:38.513919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37f449ca97f'
down_revision: Union[str, None] = 'dfa59e224900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
