"""ajuestes

Revision ID: d949354a9d65
Revises: 028e4a7674c5
Create Date: 2025-02-23 13:15:16.824894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd949354a9d65'
down_revision: Union[str, None] = '028e4a7674c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_collection', sa.Column('user_google_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_collection_user_id_fkey', 'user_collection', type_='foreignkey')
    op.create_foreign_key(None, 'user_collection', 'user', ['user_google_id'], ['google_id'])
    op.drop_column('user_collection', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_collection', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_collection', type_='foreignkey')
    op.create_foreign_key('user_collection_user_id_fkey', 'user_collection', 'user', ['user_id'], ['id'])
    op.drop_column('user_collection', 'user_google_id')
    # ### end Alembic commands ###
