"""ajueste

Revision ID: d9b316a6b77a
Revises: 34d4fcc18626
Create Date: 2025-03-01 16:20:14.172896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b316a6b77a'
down_revision: Union[str, None] = '34d4fcc18626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'collection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'user_id')
    # ### end Alembic commands ###
