"""ajuestes

Revision ID: ddb4e761a251
Revises: d2e9ea89ff9a
Create Date: 2025-03-04 11:29:09.705148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb4e761a251'
down_revision: Union[str, None] = 'd2e9ea89ff9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'session_id')
    # ### end Alembic commands ###
