"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: dfa59e224900
Revises: 5e08226cc823
Create Date: 2025-04-18 11:18:54.183910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa59e224900'
down_revision: Union[str, None] = '5e08226cc823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
