"""adicioanndo property

Revision ID: dfd1bc0ee4ae
Revises: f439ff0e692f
Create Date: 2025-03-14 16:58:24.537421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd1bc0ee4ae'
down_revision: Union[str, None] = 'f439ff0e692f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('property', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'property')
    # ### end Alembic commands ###
