"""orders

Revision ID: e504c665308c
Revises: b0956b55f110
Create Date: 2025-03-28 15:41:24.731423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e504c665308c'
down_revision: Union[str, None] = 'b0956b55f110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('protocol', sa.String(), nullable=False))
    op.alter_column('order', 'last_payment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('order', 'status')
    op.drop_column('order', 'amount')
    op.drop_column('order', 'payment_id')
    op.drop_column('order', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('order', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'last_payment',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('order', 'protocol')
    # ### end Alembic commands ###
