"""Corrigindo relacionamento entre Post, Midia e PostMidia

Revision ID: e72373d2b82a
Revises: fb008ab8928e
Create Date: 2025-04-18 00:12:05.177184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72373d2b82a'
down_revision: Union[str, None] = 'fb008ab8928e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
