"""ajustes

Revision ID: e91badc2f4da
Revises: 50548a70e110
Create Date: 2025-04-26 13:43:14.456564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91badc2f4da'
down_revision: Union[str, None] = '50548a70e110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'category')
    # ### end Alembic commands ###
