"""index

Revision ID: e984b9216129
Revises: 8abb287ede6f
Create Date: 2025-03-25 19:38:07.110836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e984b9216129'
down_revision: Union[str, None] = '8abb287ede6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipe_session_id'), 'recipe', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_session_id'), table_name='recipe')
    # ### end Alembic commands ###
