"""Corrigindo description com server_default

Revision ID: ea4908fe012a
Revises: 6a48ba9ea24e
Create Date: 2025-02-16 09:50:19.729443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4908fe012a'
down_revision: Union[str, None] = '6a48ba9ea24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('description', sa.String(), server_default='Sem descrição', nullable=False))
    op.add_column('recipe', sa.Column('preparation_time', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('recipe', sa.Column('serving_size', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'serving_size')
    op.drop_column('recipe', 'preparation_time')
    op.drop_column('recipe', 'description')
    # ### end Alembic commands ###
