"""ajuestes

Revision ID: eef3ef6b2a98
Revises: 4874d115e60e
Create Date: 2025-02-23 10:21:48.616354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef3ef6b2a98'
down_revision: Union[str, None] = '4874d115e60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_session_id_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_collection_id_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'collection_id')
    op.drop_column('recipe', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_collection_id_fkey', 'recipe', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('recipe_session_id_fkey', 'recipe', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
