"""ajuste

Revision ID: efd93da2cf3d
Revises: 67d18c091fd3
Create Date: 2025-03-13 16:06:09.724308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd93da2cf3d'
down_revision: Union[str, None] = '67d18c091fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('youtube_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'youtube_url')
    # ### end Alembic commands ###
