"""ajuestes

Revision ID: f439ff0e692f
Revises: efd93da2cf3d
Create Date: 2025-03-14 16:25:52.906562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f439ff0e692f'
down_revision: Union[str, None] = 'efd93da2cf3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('property', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'property')
    # ### end Alembic commands ###
