"""shopping list

Revision ID: fc54245b7a09
Revises: 1f24bc5aea5a
Create Date: 2025-04-21 15:48:31.124663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc54245b7a09'
down_revision: Union[str, None] = '1f24bc5aea5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shopping_list', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list', 'updated_at')
    op.drop_column('shopping_list', 'created_at')
    # ### end Alembic commands ###
