"""shopping list

Revision ID: fde8e2b87199
Revises: e0d9a936469c
Create Date: 2025-04-21 15:05:40.188182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde8e2b87199'
down_revision: Union[str, None] = 'e0d9a936469c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_item',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unity', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_item_id'), 'shopping_item', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_item_name'), 'shopping_item', ['name'], unique=False)
    op.create_index(op.f('ix_shopping_item_price'), 'shopping_item', ['price'], unique=False)
    op.create_index(op.f('ix_shopping_item_quantity'), 'shopping_item', ['quantity'], unique=False)
    op.create_index(op.f('ix_shopping_item_recipe_id'), 'shopping_item', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_shopping_item_unity'), 'shopping_item', ['unity'], unique=False)
    op.create_index(op.f('ix_shopping_item_user_id'), 'shopping_item', ['user_id'], unique=False)
    op.create_table('shopping_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_id'), 'shopping_list', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_list_name'), 'shopping_list', ['name'], unique=False)
    op.create_index(op.f('ix_shopping_list_recipe_id'), 'shopping_list', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_user_id'), 'shopping_list', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_user_id'), table_name='shopping_list')
    op.drop_index(op.f('ix_shopping_list_recipe_id'), table_name='shopping_list')
    op.drop_index(op.f('ix_shopping_list_name'), table_name='shopping_list')
    op.drop_index(op.f('ix_shopping_list_id'), table_name='shopping_list')
    op.drop_table('shopping_list')
    op.drop_index(op.f('ix_shopping_item_user_id'), table_name='shopping_item')
    op.drop_index(op.f('ix_shopping_item_unity'), table_name='shopping_item')
    op.drop_index(op.f('ix_shopping_item_recipe_id'), table_name='shopping_item')
    op.drop_index(op.f('ix_shopping_item_quantity'), table_name='shopping_item')
    op.drop_index(op.f('ix_shopping_item_price'), table_name='shopping_item')
    op.drop_index(op.f('ix_shopping_item_name'), table_name='shopping_item')
    op.drop_index(op.f('ix_shopping_item_id'), table_name='shopping_item')
    op.drop_table('shopping_item')
    # ### end Alembic commands ###
